name: flutter_login_vk
description: Login via VK.com. Easily add VK login feature in your application. User profile information included.
version: 2.2.3
homepage: https://github.com/Innim/flutter_login_vk
repository: https://github.com/Innim/flutter_login_vk
issue_tracker: https://github.com/Innim/flutter_login_vk/issues

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  async:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ru.innim.flutter_login_vk
        pluginClass: FlutterLoginVkPlugin
      ios:
        pluginClass: FlutterLoginVkPlugin
